apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::706355158413:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-9KD6J5YO70tU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
        - system:masters
      rolearn: arn:aws:iam::706355158413:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system